name: Deploy to Google Cloud Platform

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"
  packages: "read"

jobs:
  build_and_push_gcp:
    runs-on: ubuntu-22.04
    env:
      REGISTRY_GCP: us-central1-docker.pkg.dev/cicd-demo-460905
      REPOSITORY_GCP: my-docker-repo
      IMAGE_NAME: my-app
      IMAGE_TAG: latest
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Create env file for Docker secrets
        run: |
          touch .env.docker
          echo "NODE_ENV=production" > .env.docker

      - name: Build Docker image
        run: |
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          DOCKER_BUILDKIT=1 docker build \
            -t ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            --build-arg BUILD_DATE="${BUILD_DATE}" \
            --build-arg VCS_REF="${{ env.COMMIT_SHA }}" \
            --build-arg VERSION="${{ env.IMAGE_TAG }}" \
            --build-arg BUILD_NUMBER="${{ github.run_number }}" \
            --secret id=env,src=.env.docker \
            .

      - name: Clean up env file
        run: rm .env.docker

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Tag image for Google Cloud
        run: |
          # Tag with latest
          docker tag ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          # Tag with commit SHA
          docker tag ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}

      - name: Push image to Artifact Registry
        run: |
          # Push latest tag
          docker push ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          # Push commit SHA tag
          docker push ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}

      - name: Add image descriptions and annotations
        run: |
          # Set description for the latest tag
          gcloud artifacts docker images describe \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --format="value(name)" > /dev/null || true

          # Add annotations to the image
          gcloud artifacts docker images add-tag \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }} \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:build-${{ github.run_number }} || true

          # You can also use gcloud to add custom metadata
          echo "Image pushed successfully with the following details:"
          echo "- Repository: ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}"
          echo "- Tags: ${{ env.IMAGE_TAG }}, ${{ env.COMMIT_SHA }}, build-${{ github.run_number }}"
          echo "- Build Date: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "- Commit SHA: ${{ env.COMMIT_SHA }}"
          echo "- Build Number: ${{ github.run_number }}"
