name: Deploy to Google Cloud Platform

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"
  packages: "read"

jobs:
  build_and_push_gcp:
    runs-on: ubuntu-22.04
    env:
      REGISTRY_GCP: us-central1-docker.pkg.dev/cicd-demo-460905
      REPOSITORY_GCP: my-docker-repo
      IMAGE_NAME: my-app
      IMAGE_TAG: latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Create env file for Docker secrets
        run: |
          touch .env.docker
          echo "NODE_ENV=production" > .env.docker

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            -t ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            --secret id=env,src=.env.docker \
            .

      - name: Clean up env file
        run: rm .env.docker

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Tag image for Google Cloud
        run: |
          docker tag ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Push image to Artifact Registry
        run: |
          docker push ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-22.04
    needs: [build_and_push_gcp]
    env:
      CLUSTER_NAME: my-gke-cluster
      CLUSTER_ZONE: us-central1
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_ZONE }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/my-app-deployment \
            my-app=${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            -n default
          kubectl rollout status deployment/my-app-deployment -n default
