name: Deploy to Google Cloud Platform

on:
  push:
    branches:
      - main

permissions:
  contents: "read"
  id-token: "write"
  packages: "read"

jobs:
  build_and_push_gcp:
    runs-on: ubuntu-22.04
    env:
      REGISTRY_GCP: us-central1-docker.pkg.dev/cicd-demo-460905
      REPOSITORY_GCP: my-docker-repo
      IMAGE_NAME: my-app
      IMAGE_TAG: latest
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for tags

      - name: Get version from Git tag
        id: version
        run: |
          # Get the latest tag, fallback to 'dev' if no tags exist
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev")
          # Keep the 'v' prefix (v1.2.3 stays as v1.2.3)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Create env file for Docker secrets
        run: |
          touch .env.docker
          echo "NODE_ENV=production" > .env.docker

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            -t ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            --secret id=env,src=.env.docker \
            .

      - name: Clean up env file
        run: rm .env.docker

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Tag image for Google Cloud
        run: |
          # Tag with latest
          docker tag ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          # Tag with commit SHA
          docker tag ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}

          # Tag with version
          docker tag ${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }} \
            ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}

      - name: Push image to Artifact Registry
        run: |
          # Push latest tag
          docker push ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          # Push commit SHA tag
          docker push ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_SHA }}

          # Push version tag
          docker push ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}

          - name: Set description for Docker image in Artifact Registry
          run: |
            gcloud artifacts docker images update ${{ env.REGISTRY_GCP }}/${{ env.REPOSITORY_GCP }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --description="Version: ${{ env.IMAGE_TAG }}"
